### ISSUE TITLE
Adding header file for GUID in NetTransportLayer.h

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Internal#20]
We are using the Windows typedef GUID in NetTransportLayer.h, but no header is defined containing the definition. When I ask VS to goto the definition, it opens guiddef.h.

Researching online, it seems to recommend using rpc.h. 

To clean this up, not really sure which header we should use (if any) as it seems to be compiling fine.

Discovered it toying around trying to get op2ext to load the NetFix dll.

-Brett

**Comment by DanRStevens** [comment]
For reference:
[MSDN: `GUID` structure](https://msdn.microsoft.com/en-us/library/windows/desktop/aa373931%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

It does indeed list `Rpc.h` as the include.

I'm guessing `GUID` is being included indirectly from one of the other Windows includes. There are quite a few of them. Quite possibly it's being included by [`objbase.h`](https://docs.microsoft.com/en-us/windows/desktop/api/objbase/). `GUID`s are pretty fundamental to COM, used for interface IDs and class IDs.
