### ISSUE TITLE
Add Test project

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Internal#29]
The project folder should probably be organized into `src/` and `test/` folders, with a test project added.

The test project should have code which calls each function. The calls do not necessarily need to be valid, or even run, they just need to be, at minimum, present in a source file. This may be sufficient to force the Linker to lookup the symbol of each called method, and ensure it is present. This would help catch missing exported names from the .asm file, and name mangling changes caused by method signature updates.

In particular, marking a method as `const`, or changing from a `class` to a `struct` has the potential to change the mangled name of a method.

Proposed structure:
```
README.md
makefile
OP2Internal.sln
src/
  OP2Internal.vcxproj
  OP2Internal.vcxproj.filters
  OP2Internal.h
  OP2Internal.asm
  PointTypes.h
  WinTypes.h
  Game/
  Network/
  ResourceManagement/
  UserInterface
test/
  Test.vcxproj
  DummyMain.cpp  // We may want to rename this later
```

**Comment by Brett208** [comment]
Generally agree with this idea. Hopefully the compiler & linker are not smart enough to ignore empty functions.

Would it be appropriate to use gtest here?

-Brett

**Comment by DanRStevens** [comment]
It may be appropriate to use gtest here. Particularly if we actually start calling functions for real and testing results. I think we should have that eventually.

As for the immediate checks for name mangling problems, we get that during compilation, rather than running. Hence just being able to compile a test project would give us advance warning for name mangling problems.

@Brett208, could you create a new Test project for this repository? You may add gtest to it if convenient, though that isn't required immediately.

**Comment by Brett208** [comment]
I'll get it setup this weekend.

-Brett

**Comment by Brett208** [comment]
I'm closing this since the test project is now in master. Remeber in current configuration, no gmock on MSVC and no explicitly building as C++17 for MSVC. Would still be nice to improve our gtest build at some point for Windows, but am planning to focus on other issues.

**Comment by DanRStevens** [comment]
Sounds good. Thanks for handling this so quickly.
