### ISSUE TITLE
Create a custom build event for .asm files

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Internal#9]
Use NetFixClient to test if the custom build event is working

**Comment by DanRStevens** [comment]
Once NASM is setup, you should be able to see Visual Studio compile the .asm file to a .obj file in the build log. Though yes, to test if things link up correctly and run, that would be easier to do from the context of the NetFixClient.

----

Taken from the earlier discussion in PR https://github.com/OutpostUniverse/NetFixClient/pull/5 :

Looking back at the old project file, the settings were:
```
SOURCE=.\ForcedExports.asm
# Begin Custom Build
IntDir=.\Release
InputPath=.\ForcedExports.asm
InputName=ForcedExports

"$(IntDir)\$(InputName).obj" : $(SOURCE) "$(INTDIR)" "$(OUTDIR)"
       NASM -f win32 -o "$(IntDir)\$(InputName).obj" "$(InputPath)"
```

For reference: [NASM Manual - Options](https://www.nasm.us/xdoc/2.12.01/html/nasmdoc2.html#section-2.1.2)
`-f` sets the output format
`-o` sets the output filename (.obj)
The input filename is simply given, here at the end.

**Comment by Brett208** [comment]
Since we have a custom build event working, I'm going to close this.
